const CONFIG = {
    introTitle: 'Babe à!',
    introDesc: `Anh có điều này muốn hỏi em, nhớ phải trả lời thật lòng nhaaa`,
    btnIntro: 'hihi',
    title: 'Em có yêu anh không nào?',
    desc: 'Em mà thoát ra là năm sau chúng ta cưới luôn đó =))))',
    btnYes: 'Yêu ơi là yêu ❤❤',
    btnNo: 'Không ghét anh lắm 😒',
    question:'Cùng nhau thực hiện lời hứa nhaaa',
    btnReply: 'Gửi cho anh <3',
    reply: 'Dạaaa <33333333',
    mess: 'Yêu em nhiều nhiều 😘😘',
    messDesc: 'Hết cách ly anh đưa bé đi lượn nhaa',
    btnAccept: 'Okiiiii lun <3',
